### PR TITLE
fix bug of aljad and getSharhPrefix

### LINKED ISSUE #6: Replace getName with getSharhPrefix in some mirath methods
replace `getName(nbr)` with `getSharhPrefix(nbr)` in sharh of mirath of:

- abna_alikhwa_alashika
- abna_alikhwa_li_ab
- ala3mam_alashika
- ala3mam_li_ab
- abna_ala3mam_alashika
- abna_ala3mam_li_ab

### LINKED ISSUE #7: Bug in sharh of mirath aljad (textual form)
In the case of mirath aljad when `far3_warith_ontha` is present, and no `far3_warith_dhakar` and no `alikhwa_alashika_wa_li_ab` .

The bug has been fixed.

### PR DESCRIPTION
**Pull request by haithemGuef**
fixes #7

### CODE REVIEW

**Review by cdjalel — CHANGES_REQUESTED** [review]
Change at line 322 is wrong. The old code should be kept as it is correct.
That line states only that Aljad doesn't share Albaqi with Alikhwa. There could be far3 warith ontha or not.
The latter is handler eariler.

Also, it seems your fork is not updated with the latest changes on my HEAD branch. As this line you try to change (322) has number 327 in my code

**Comment by haithemGuef** [comment]
the last (else) at the line 327 initialise the variable `sharh` with `getSharhPrefix()` even with `far3_warith_ontha` is present, and the result will be (الجد يرث الباقي تعصيبا بالنفس) instead of (الجد يرث السدس 1\6 فرضا + الباقي تعصيبا بالنفس)

this is the part of the code:


```
ta3seeb = true;
                if (far3_warith_ontha) {
                    sharh = Warith.ALJAD.getSharhPrefix();
                    sharh += "السدس 1\\6 فرضا + ";
                    bast = 1;
                    maqam = 6;
                } else {             // الجد يرث الباقي فقط
                    sharh = "";
                    bast = 0;
                    maqam = 1;
                }
                if (alikhwa_alashika_wa_li_ab) {        // الجد يُقاسم الإخوة
                    if (mInput.get_alikhwa_alashika() > 0) {
                        ro2os += mInput.get_alikhwa_alashika();
                        if (mInput.get_alakhawat_ashakikat() > 0) {
                            ro2os *= 2;
                            ro2os += mInput.get_alakhawat_ashakikat();
                            mTassawi = tassawi = false;
                        } else {
                            tassawi = true;
                        }
                        sharh += Warith.ALJAD.getSharhPrefix(1, Warith.ALIKHWA_ALASHIKA, mInput.get_alikhwa_alashika(), tassawi);
                    } else {  // mInput.get_alikhwa_li_ab() > 0
                        ro2os += mInput.get_alikhwa_li_ab();
                        if (mInput.get_alakhawat_li_ab() > 0) {
                            ro2os *= 2;
                            ro2os += mInput.get_alikhwa_li_ab();
                            mTassawi = tassawi = false;
                        } else {
                            tassawi = true;
                        }
                        sharh += Warith.ALJAD.getSharhPrefix(1, Warith.ALIKHWA_LI_AB, mInput.get_alikhwa_li_ab(), tassawi);
                    }
                    mJadIndex = mWarathah.size();
                }
                else {       // الجد يرث الباقي لوحده
                    sharh = Warith.ALJAD.getSharhPrefix();
                }
                sharh += "الباقي تعصيبا بالنفس";

```

image

**Comment by cdjalel** [comment]
OK I see the issue now. The problem is with the Sharh message for Aljad in the case of a  Far3 warith ontha. So the logic is still fine as shown in the table. The else statement in question should not be modified to test on far3_warith_ontha again.
Instead, the nest line where sharh is assigned should be an incrementatl assignement (with += ) and a not  reset that removes the 1/6 string.
The fix should be in line [328](https://github.com/cdjalel/Zaid/blob/master/app/src/main/java/com/djalel/android/zaid/Massala.java#L328): sharh **+**= Warith.ALJAD.getSharhPrefix();

Please change the fix as explained.
BTW, no need to copy sections of the ocde here but just link to them. Like the line above.

**Comment by haithemGuef** [comment]
the bug was fixed as required

**Pull request merged**
